name: Generate dependency diff

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v6

      - id: dependency-diff
        name: Generate dependency diff
        uses: usefulness/dependency-tree-diff-action@v2
        with:
          project: 'livekit-android-sdk'

      - name: Log dependency diff
        run: |
          echo "Dependency diff:"
          echo "${{ steps.dependency-diff.outputs.text-diff }}"

      - uses: peter-evans/find-comment@v4
        if: github.event.pull_request.head.repo.full_name == github.repository
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Dependency diff

      - uses: peter-evans/create-or-update-comment@v5
        if: github.event.pull_request.head.repo.full_name == github.repository && (steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null)
        with:
          body: |
            Dependency diff:
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
